/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LinkConfigPanel.java
 *
 * Created on 05.01.2011, 10:13:20
 */

package org.kaiec.retro.listview;

/**
 *
 * @author kai
 */
public class LinkConfigPanel extends javax.swing.JPanel {


    private ExternalLink link;

    public ExternalLink getUpdatedLink() {
        link.setName(nameField.getText());
        link.setUrl(urlArea.getText());
        if (encodingBox.getSelectedItem()!=null) {
            link.setEncoding(encodingBox.getSelectedItem().toString());
        }
        if (replaceBox.getSelectedItem()!=null) {
            link.getReplacements().put("##1##",replaceBox.getSelectedItem().toString());
        }
        if (replaceBox1.getSelectedItem()!=null) {
            link.getReplacements().put("##2##",replaceBox1.getSelectedItem().toString());
        }
        return link;
    }

    /** Creates new form LinkConfigPanel */
    public LinkConfigPanel(ExternalLink link) {
        this.link = link;
        initComponents();
        encodingBox.removeAllItems();
        encodingBox.addItem("ISO8859-15");
        encodingBox.addItem("UTF-8");
        replaceBox.removeAllItems();
        replaceBox.addItem(ExternalLink.TITLE);
        replaceBox.addItem(ExternalLink.PPN);
        replaceBox.addItem(ExternalLink.SIGNATUR);
        replaceBox.addItem(ExternalLink.KEYWORDS);
        replaceBox.addItem(ExternalLink.FIRST_AUTHOR_LASTNAME);
        replaceBox1.removeAllItems();
        replaceBox1.addItem(ExternalLink.TITLE);
        replaceBox1.addItem(ExternalLink.PPN);
        replaceBox1.addItem(ExternalLink.SIGNATUR);
        replaceBox1.addItem(ExternalLink.KEYWORDS);
        replaceBox1.addItem(ExternalLink.FIRST_AUTHOR_LASTNAME);

        // Load fields
        nameField.setText(link.getName());
        urlArea.setText(link.getUrl());
        encodingBox.setSelectedItem(link.getEncoding());
        replaceBox.setSelectedItem(link.getReplacements().get("##1##"));
        replaceBox1.setSelectedItem(link.getReplacements().get("##2##"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urlArea = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        replaceBox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        encodingBox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        replaceBox1 = new javax.swing.JComboBox();

        jLabel1.setText(org.openide.util.NbBundle.getMessage(LinkConfigPanel.class, "LinkConfigPanel.jLabel1.text")); // NOI18N

        nameField.setText(org.openide.util.NbBundle.getMessage(LinkConfigPanel.class, "LinkConfigPanel.nameField.text")); // NOI18N

        jLabel2.setText(org.openide.util.NbBundle.getMessage(LinkConfigPanel.class, "LinkConfigPanel.jLabel2.text")); // NOI18N

        urlArea.setColumns(20);
        urlArea.setLineWrap(true);
        urlArea.setRows(5);
        jScrollPane1.setViewportView(urlArea);

        jLabel3.setText(org.openide.util.NbBundle.getMessage(LinkConfigPanel.class, "LinkConfigPanel.jLabel3.text")); // NOI18N

        replaceBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText(org.openide.util.NbBundle.getMessage(LinkConfigPanel.class, "LinkConfigPanel.jLabel4.text")); // NOI18N

        encodingBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText(org.openide.util.NbBundle.getMessage(LinkConfigPanel.class, "LinkConfigPanel.jLabel5.text")); // NOI18N

        replaceBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                            .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(replaceBox, 0, 274, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(encodingBox, 0, 274, Short.MAX_VALUE)
                            .addComponent(replaceBox1, 0, 274, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(replaceBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encodingBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox encodingBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JComboBox replaceBox;
    private javax.swing.JComboBox replaceBox1;
    private javax.swing.JTextArea urlArea;
    // End of variables declaration//GEN-END:variables

}
